insert into prismas.campos_alarma_prisma values('deformacion_radial','deformacion_radial');
insert into prismas.campos_alarma_prisma values('velocidad_radial','velocidad_radial');
insert into prismas.campos_alarma_prisma values('aceleracion_radial','aceleracion_radial');
insert into prismas.campos_alarma_prisma values('def_ma_radial','def_ma_radial');
insert into prismas.campos_alarma_prisma values('def_ewma_radial','def_ewma_radial');
insert into prismas.campos_alarma_prisma values('vel_ma_radial','vel_ma_radial');
insert into prismas.campos_alarma_prisma values('vel_ewma_radial','vel_ewma_radial');
insert into prismas.campos_alarma_prisma values('acel_ma_radial','acel_ma_radial');
insert into prismas.campos_alarma_prisma values('acel_ewma_radial','acel_ewma_radial');